version: 2.1
workflows:
  semgrep:
    jobs:
      - semgrep-full-scan:
          filters:
            branches:
              only: main
          context:
            - semgrep
      - semgrep-diff-scan:
          filters:
            branches:
              ignore: main
          context:
            - semgrep
jobs:
  semgrep-full-scan:
    docker:
      - image: semgrep/semgrep
    steps:
      - checkout
      - run:
          name: "Semgrep full scan"
          environment: 
            SEMGREP_REPO_URL: https://github.com/semgrep-priv-test/semgrep-react.git
          command: semgrep ci     
  semgrep-diff-scan:
    parameters:
      default_branch:
        type: string
        default: main
    docker:
      - image: semgrep/semgrep
    steps:
      - checkout
      - run: 
          name: Semgrep diff scan
          environment: 
            SEMGREP_BASELINE_REF: << parameters.default_branch >>
            SEMGREP_REPO_URL: https://github.com/semgrep-priv-test/semgrep-react.git
          command: semgrep ci
